export const propertiesWordShortMap: Record<string, string> = {
  min: 'mn',
  max: 'mx',
  width: 'w',
  height: 'h',
  transform: 'trnsf',
  transition: 'trnst',
  translate: 'trnsl',
  overflow: 'of',
  boxShadow: 'shadow',
  background: 'bg',
  position: 'pos',
  perspective: 'per',
  gap: 'gap',
};
